import { 
  Shield, 
  Lock, 
  Database, 
  Cookie, 
  Mail, 
  Eye, 
  Trash2,
  Server
} from "lucide-react";

export const metadata = {
  title: "Privacy Policy | JaksLab",
  description: "How JaksLab collects, uses, and protects your personal data.",
};

export default function PrivacyPolicy() {
  return (
    <main className="min-h-screen bg-transparent text-slate-300 py-24 px-6 lg:px-20">
      <div className="max-w-4xl mx-auto space-y-12">
        
        {/* Header */}
        <div className="text-center space-y-4">
          <div className="w-16 h-16 mx-auto bg-blue-500/10 text-blue-500 rounded-full flex items-center justify-center mb-6">
            <Shield size={32} />
          </div>
          <h1 className="text-4xl md:text-5xl font-black text-white tracking-tight">
            Privacy Policy
          </h1>
          <p className="text-slate-400 text-lg max-w-2xl mx-auto">
            Last Updated: March 5, 2026
          </p>
          <p className="text-sm text-slate-500 max-w-2xl mx-auto mt-4 uppercase tracking-widest font-semibold">
            In keeping with our commitment to confidentiality, your information is kept strictly secure.
          </p>
        </div>

        {/* Content */}
        <div className="bg-white/[0.02] border border-white/5 p-8 md:p-12 rounded-[2.5rem] space-y-12 shadow-2xl relative overflow-hidden">
          <div className="absolute -top-24 -right-24 w-64 h-64 bg-blue-600/5 blur-[100px] rounded-full pointer-events-none"></div>

          {/* Intro Section */}
          <section className="space-y-4 relative z-10">
            <p className="leading-relaxed text-slate-400">
              This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p className="leading-relaxed text-slate-400">
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>
          </section>

          {/* Section 1: Definitions */}
          <section className="space-y-6 relative z-10">
            <div className="border-b border-white/10 pb-2 mb-6 mt-8">
              <h2 className="text-3xl font-black text-white flex items-center gap-3">
                <Database size={24} className="text-blue-500" />
                1. Interpretation and Definitions
              </h2>
            </div>
            
            <ul className="space-y-4 text-slate-400">
              <li><strong className="text-white">Account:</strong> A unique account created for You to access our Service.</li>
              <li><strong className="text-white">Company:</strong> (referred to as "the Company", "We", "Us" or "Our") refers to Jaks-Tech / JaksLab, Nairobi, Kenya.</li>
              <li><strong className="text-white">Cookies:</strong> Small files placed on Your device containing the details of Your browsing history on that website.</li>
              <li><strong className="text-white">Device:</strong> Any device that can access the Service such as a computer, cellphone, or digital tablet.</li>
              <li><strong className="text-white">Personal Data:</strong> Any information that relates to an identified or identifiable individual.</li>
              <li><strong className="text-white">Service / Website:</strong> Refers to JaksLab, accessible from https://www.jakslab.work/.</li>
              <li><strong className="text-white">Usage Data:</strong> Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            </ul>
          </section>

          {/* Section 2: Data Collection */}
          <section className="space-y-6 relative z-10">
            <div className="border-b border-white/10 pb-2 mb-6 mt-8">
              <h2 className="text-3xl font-black text-white flex items-center gap-3">
                <Eye size={24} className="text-blue-500" />
                2. Collecting Your Personal Data
              </h2>
            </div>

            <div className="space-y-4">
              <h3 className="text-xl font-bold text-white">Types of Data Collected</h3>
              <p className="leading-relaxed text-slate-400">
                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You, including:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-slate-400">
                <li>Email address (mandatory)</li>
                <li>First name and last name</li>
                <li>Phone number and preferred platform (e.g., WhatsApp, Telegram)</li>
                <li>Project details (e.g., university name, course, technical requirements)</li>
                <li>Usage Data (e.g., IP address, browser type, pages visited)</li>
              </ul>
              <p className="leading-relaxed text-slate-400 mt-4 italic">
                Note: We do not save any details of your transactions, such as credit card details or secure banking passwords on our servers. Payments are handled completely by secure third-party payment gateways.
              </p>
            </div>
          </section>

          {/* Section 3: Cookies */}
          <section className="space-y-6 relative z-10">
            <div className="border-b border-white/10 pb-2 mb-6 mt-8">
              <h2 className="text-3xl font-black text-white flex items-center gap-3">
                <Cookie size={24} className="text-blue-500" />
                3. Tracking Technologies and Cookies
              </h2>
            </div>
            <p className="leading-relaxed text-slate-400">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to improve and analyze Our Service.
            </p>
            <ul className="list-disc pl-6 space-y-2 text-slate-400">
              <li><strong className="text-white">Necessary/Essential Cookies:</strong> Essential to provide You with services available through the Website and enable You to use some of its features.</li>
              <li><strong className="text-white">Functionality Cookies:</strong> Allow us to remember choices You make when You use the Website, such as your login details.</li>
            </ul>
          </section>

          {/* Section 4: Use of Data */}
          <section className="space-y-6 relative z-10">
            <div className="border-b border-white/10 pb-2 mb-6 mt-8">
              <h2 className="text-3xl font-black text-white flex items-center gap-3">
                <Server size={24} className="text-blue-500" />
                4. Use of Your Personal Data
              </h2>
            </div>
            <p className="leading-relaxed text-slate-400">We may use Personal Data for the following purposes:</p>
            <ul className="list-disc pl-6 space-y-2 text-slate-400">
              <li><strong className="text-white">To provide and maintain our Service:</strong> Including monitoring the usage of our Service.</li>
              <li><strong className="text-white">To manage Your requests:</strong> To attend and manage Your project requests, custom development, and academic orders.</li>
              <li><strong className="text-white">To contact You:</strong> By email, phone, or SMS regarding updates, informative communications, or security notices.</li>
              <li><strong className="text-white">To provide news and offers:</strong> About services similar to those you have enquired about, unless You have opted not to receive such information.</li>
            </ul>
            <p className="leading-relaxed text-slate-400 font-bold mt-4">
              We never share Your personal details or project data with third-party marketers.
            </p>
          </section>

          {/* Section 5: Disclosure & Security */}
          <section className="space-y-6 relative z-10">
            <div className="border-b border-white/10 pb-2 mb-6 mt-8">
              <h2 className="text-3xl font-black text-white flex items-center gap-3">
                <Lock size={24} className="text-blue-500" />
                5. Disclosure and Security
              </h2>
            </div>
            <p className="leading-relaxed text-slate-400">
              We may disclose Your Personal Data in the good faith belief that such action is necessary to comply with a legal obligation, protect and defend the rights or property of the Company, or protect the personal safety of Users.
            </p>
            <p className="leading-relaxed text-slate-400">
              The security of Your Personal Data is important to Us. While We strive to use commercially acceptable means to protect Your Personal Data (including strict NDAs for our developers and experts), remember that no method of transmission over the Internet is 100% secure.
            </p>
          </section>

          {/* Section 6: Deletion */}
          <section className="space-y-6 relative z-10">
            <div className="border-b border-white/10 pb-2 mb-6 mt-8">
              <h2 className="text-3xl font-black text-white flex items-center gap-3">
                <Trash2 size={24} className="text-blue-500" />
                6. User Data Deletion Policy
              </h2>
            </div>
            <p className="leading-relaxed text-slate-400">
              JaksLab provides users with full control over their data. You can request all or part of your data (including project files and personal contact details) to be permanently deleted from our servers by sending an email to <strong>hello@jakslab.work</strong>.
            </p>
          </section>

          {/* Footer Contact Box */}
          <div className="mt-12 p-8 bg-blue-500/5 rounded-3xl border border-blue-500/10 text-center space-y-4 relative z-10">
            <Mail className="mx-auto text-blue-400 mb-2" size={32} />
            <h3 className="text-2xl font-bold text-white">Contact Us</h3>
            <p className="text-slate-400">
              If you have any questions about this Privacy Policy or are looking for a resolution of any data privacy issues, please contact us:
            </p>
            <div className="pt-4">
              <a 
                href="mailto:hello@jakslab.work"
                className="inline-flex items-center gap-2 px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-xl font-semibold transition-colors"
              >
                hello@jakslab.work
              </a>
            </div>
            <p className="text-sm text-slate-500 mt-4">
              JaksLab is committed to protecting Your privacy and ensuring the security of Your Personal Data.
            </p>
          </div>

        </div>
      </div>
    </main>
  );
}